# Generated by Django 5.2.6 on 2025-09-18 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_remove_application_property_application_created_by_and_more'),
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название счёта')),
                ('details', models.TextField(blank=True, verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Счёт получателя',
                'verbose_name_plural': 'Счета получателей',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название типа платежа')),
            ],
            options={
                'verbose_name': 'Тип платежа',
                'verbose_name_plural': 'Типы платежей',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма платежа')),
                ('currency', models.CharField(choices=[('UZS', 'Узбекский сум'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='UZS', max_length=3, verbose_name='Валюта')),
                ('method', models.CharField(choices=[('CASH', 'Наличные'), ('CASHLESS', 'Безналичные')], max_length=10, verbose_name='Вид платежа')),
                ('due_date', models.DateField(verbose_name='Дата к оплате')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата фактической оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('beneficiary_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.beneficiaryaccount', verbose_name='Счёт получателя')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crm.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='deals.deal', verbose_name='Сделка')),
                ('responsible_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_payments', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.paymenttype', verbose_name='Тип платежа')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Совершенное действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finances.payment', verbose_name='Платёж')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог платежа',
                'verbose_name_plural': 'Логи платежей',
                'ordering': ['-created_at'],
            },
        ),
    ]
