# Generated by Django 5.2.6 on 2025-10-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'К оплате'), ('PAID', 'Оплачен'), ('OVERDUE', 'Просрочен'), ('TO_BE_RETURNED', 'К возврату'), ('RETURNED', 'Возвращен')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
    ]
