# Generated by Django 5.2.6 on 2026-02-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_payment_status'),
        ('permissions', '0008_alter_partnerapikey_allowed_scopes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='permissions.company', verbose_name='Компания'),
        ),
    ]
