# Generated by Django 5.2.6 on 2026-03-06 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_payment_company'),
        ('permissions', '0011_alter_partnerapikey_key_encrypted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryaccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_accounts', to='permissions.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='beneficiaryaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_beneficiary_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
    ]
