# Generated by Django 5.2.6 on 2026-09-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_beneficiaryaccount_company_and_more'),
        ('permissions', '0011_alter_partnerapikey_key_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='permissions.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название типа платежа'),
        ),
        migrations.AlterUniqueTogether(
            name='paymenttype',
            unique_together={('company', 'name')},
        ),
    ]
