# Generated by Django 5.2.6 on 2026-09-10 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_performance_indexes'),
        ('deals', '0008_performance_indexes'),
        ('finances', '0005_company_isolation'),
        ('permissions', '0011_alter_partnerapikey_key_encrypted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'due_date'], name='finances_pa_status_70e21f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'status'], name='finances_pa_company_796356_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='finances_pa_payment_1d61c0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['deal'], name='finances_pa_deal_id_576b32_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['responsible_employee', 'status'], name='finances_pa_respons_7e4ed2_idx'),
        ),
    ]
