# Generated by Django 5.2.6 on 2026-10-05 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_performance_indexes'),
        ('permissions', '0012_multicurrency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='entered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Введённая сумма'),
        ),
        migrations.AddField(
            model_name='payment',
            name='entered_currency',
            field=models.CharField(blank=True, choices=[('UZS', 'Узбекский сум'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Российский рубль'), ('CNY', 'Китайский юань'), ('KZT', 'Казахстанский тенге'), ('GBP', 'Фунт стерлингов'), ('AED', 'Дирхам ОАЭ'), ('TRY', 'Турецкая лира')], max_length=3, verbose_name='Валюта ввода'),
        ),
        migrations.AddField(
            model_name='payment',
            name='entered_rate',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Курс пересчёта в валюту сделки'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('UZS', 'Узбекский сум'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Российский рубль'), ('CNY', 'Китайский юань'), ('KZT', 'Казахстанский тенге'), ('GBP', 'Фунт стерлингов'), ('AED', 'Дирхам ОАЭ'), ('TRY', 'Турецкая лира')], default='UZS', max_length=3, verbose_name='Валюта'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('UZS', 'Узбекский сум'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Российский рубль'), ('CNY', 'Китайский юань'), ('KZT', 'Казахстанский тенге'), ('GBP', 'Фунт стерлингов'), ('AED', 'Дирхам ОАЭ'), ('TRY', 'Турецкая лира')], max_length=3, verbose_name='Валюта')),
                ('date', models.DateField(verbose_name='Дата курса')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='Сумов за единицу валюты')),
                ('source', models.CharField(choices=[('CBU', 'ЦБ Узбекистана'), ('MANUAL', 'Введён вручную')], default='CBU', max_length=10, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='permissions.company', verbose_name='Компания (для ручного курса)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем введён')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date', 'currency'],
                'indexes': [models.Index(fields=['currency', 'date'], name='finances_ex_currenc_2bc3fa_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('currency', 'date'), name='uniq_cbu_rate_per_day'), models.UniqueConstraint(fields=('currency', 'date', 'company'), name='uniq_company_rate_per_day')],
            },
        ),
    ]
