# Generated by Django 5.2.6 on 2026-10-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_multicurrency'),
        ('permissions', '0012_multicurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveSmallIntegerField(verbose_name='Срок рассрочки, мес. (0 — полная оплата)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка за этот срок, %')),
                ('down_payment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Минимальный первоначальный взнос, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='permissions.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Условие рассрочки',
                'verbose_name_plural': 'Условия рассрочки',
                'ordering': ['months'],
                'constraints': [models.UniqueConstraint(fields=('company', 'months'), name='uniq_installment_term_per_company')],
            },
        ),
    ]
