# Generated by Django 5.2.6 on 2026-10-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_installment_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка по плану, %'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='down_payment_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Минимальный первоначальный взнос, %'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='plan_kind',
            field=models.CharField(blank=True, choices=[('FULL', 'Оплата всей суммой'), ('INSTALLMENT', 'Взнос и ежемесячные платежи'), ('DEFERRED', 'Взнос и остаток одним платежом')], default='', max_length=12, verbose_name='План оплаты'),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='plan_months',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Срок, мес.'),
        ),
        migrations.DeleteModel(
            name='InstallmentPlan',
        ),
    ]
