# Generated by Django 5.2.6 on 2026-10-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_payment_type_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='discount_percent',
        ),
    ]
