# Generated by Django 5.2.6 on 2025-10-05 12:14

from django.db import migrations, models


def migrate_role_level_to_scope_category(apps, schema_editor):
    """
    Миграция данных из старого поля level в новые поля scope и category
    """
    Role = apps.get_model('permissions', 'Role')
    
    # Маппинг старых значений на новые
    level_to_scope_category = {
        'SYSTEM_ADMIN': ('SYSTEM', 'ADMINISTRATIVE'),
        'COMPANY_ADMIN': ('COMPANY', 'ADMINISTRATIVE'),
        'DEPARTMENT_MANAGER': ('DEPARTMENT', 'MANAGEMENT'),
        'MANAGER': ('OWN', 'OPERATIONAL'),
        'VIEWER': ('COMPANY', 'READONLY'),
        'CUSTOM': ('OWN', 'CUSTOM'),
    }
    
    for role in Role.objects.all():
        old_level = role.level
        if old_level in level_to_scope_category:
            scope, category = level_to_scope_category[old_level]
            role.scope = scope
            role.category = category
            role.save(update_fields=['scope', 'category'])


def reverse_migrate_scope_category_to_level(apps, schema_editor):
    """
    Обратная миграция (если нужно откатить изменения)
    """
    Role = apps.get_model('permissions', 'Role')
    
    # Обратный маппинг
    scope_category_to_level = {
        ('SYSTEM', 'ADMINISTRATIVE'): 'SYSTEM_ADMIN',
        ('COMPANY', 'ADMINISTRATIVE'): 'COMPANY_ADMIN',
        ('DEPARTMENT', 'MANAGEMENT'): 'DEPARTMENT_MANAGER',
        ('OWN', 'OPERATIONAL'): 'MANAGER',
        ('COMPANY', 'READONLY'): 'VIEWER',
        ('OWN', 'CUSTOM'): 'CUSTOM',
    }
    
    for role in Role.objects.all():
        key = (role.scope, role.category)
        if key in scope_category_to_level:
            role.level = scope_category_to_level[key]
            role.save(update_fields=['level'])


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        # Шаг 1: Добавляем новые поля
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.CharField(
                choices=[
                    ('ADMINISTRATIVE', 'Административная'), 
                    ('MANAGEMENT', 'Управленческая'), 
                    ('OPERATIONAL', 'Операционная'), 
                    ('READONLY', 'Только просмотр'), 
                    ('CUSTOM', 'Пользовательская')
                ], 
                default='CUSTOM', 
                help_text='Группировка роли в интерфейсе пользователя', 
                max_length=30, 
                verbose_name='Категория роли'
            ),
        ),
        migrations.AddField(
            model_name='role',
            name='scope',
            field=models.CharField(
                choices=[
                    ('SYSTEM', 'Вся система'), 
                    ('COMPANY', 'Компания'), 
                    ('DEPARTMENT', 'Отдел'), 
                    ('OWN', 'Только свои данные')
                ], 
                default='OWN', 
                help_text='Определяет уровень доступа: система, компания, отдел или личные данные', 
                max_length=30, 
                verbose_name='Область действия'
            ),
        ),
        
        # Шаг 2: Мигрируем данные из level в scope и category
        migrations.RunPython(
            migrate_role_level_to_scope_category,
            reverse_migrate_scope_category_to_level
        ),
        
        # Шаг 3: Удаляем старое поле level
        migrations.RemoveField(
            model_name='role',
            name='level',
        ),
        
        # Шаг 4: Обновляем Meta
        migrations.AlterModelOptions(
            name='role',
            options={
                'ordering': ['scope', 'category', 'name'], 
                'verbose_name': 'Роль', 
                'verbose_name_plural': 'Роли'
            },
        ),
    ]
