# Generated by Django 5.2.6 on 2025-11-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_role_refactor_category_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(choices=[('CLIENT', 'Клиенты'), ('APPLICATION', 'Заявки'), ('MEETING', 'Встречи'), ('PROJECT', 'Проекты'), ('BUILDING', 'Дома'), ('PROPERTY', 'Объекты недвижимости'), ('LAYOUT', 'Планировки'), ('DISCOUNT', 'Скидки'), ('DEAL', 'Сделки'), ('PAYMENT', 'Платежи'), ('PAYMENT_TYPE', 'Типы платежей'), ('BENEFICIARY_ACCOUNT', 'Счета получателей'), ('TEMPLATE', 'Шаблоны документов'), ('REPORT', 'Отчеты'), ('PLAN', 'Планы продаж'), ('TASK', 'Задачи'), ('USER', 'Пользователи'), ('ROLE', 'Роли'), ('PERMISSION', 'Разрешения'), ('COMPANY', 'Компании'), ('DEPARTMENT', 'Отделы'), ('DASHBOARD', 'Дашборд'), ('SETTINGS', 'Настройки')], max_length=50, verbose_name='Ресурс'),
        ),
    ]
