# Generated by Django 5.2.6 on 2025-11-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_permission_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('VIEW', 'Просмотр'), ('ADD', 'Добавление'), ('EDIT', 'Редактирование'), ('DELETE', 'Удаление'), ('EXPORT', 'Экспорт'), ('IMPORT', 'Импорт'), ('APPROVE', 'Утверждение'), ('ASSIGN', 'Назначение'), ('EDIT_IN_PROGRESS', 'Редактирование задачи в работе'), ('REOPEN', 'Возврат отменённой задачи'), ('FORCE_EDIT', 'Принудительное редактирование (завершенные/отмененные задачи)'), ('DELETE_LOG', 'Удаление логов')], max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(choices=[('CLIENT', 'Клиенты'), ('APPLICATION', 'Заявки'), ('MEETING', 'Встречи'), ('PROJECT', 'Проекты'), ('BUILDING', 'Дома'), ('PROPERTY', 'Объекты недвижимости'), ('LAYOUT', 'Планировки'), ('DISCOUNT', 'Скидки'), ('DEAL', 'Сделки'), ('PAYMENT', 'Платежи'), ('PAYMENT_TYPE', 'Типы платежей'), ('BENEFICIARY_ACCOUNT', 'Счета получателей'), ('TEMPLATE', 'Шаблоны документов'), ('REPORT', 'Отчеты'), ('PLAN', 'Планы продаж'), ('TASK', 'Задачи'), ('TASK_LOG', 'Логи задач'), ('USER', 'Пользователи'), ('ROLE', 'Роли'), ('PERMISSION', 'Разрешения'), ('COMPANY', 'Компании'), ('DEPARTMENT', 'Отделы'), ('DASHBOARD', 'Дашборд'), ('SETTINGS', 'Настройки')], max_length=50, verbose_name='Ресурс'),
        ),
    ]
