# Generated by Django 5.2.6 on 2025-12-03 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_alter_permission_action_alter_permission_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(choices=[('CLIENT', 'Клиенты'), ('APPLICATION', 'Заявки'), ('MEETING', 'Встречи'), ('PROJECT', 'Проекты'), ('BUILDING', 'Дома'), ('BUILDING_TYPE', 'Типы домов'), ('PROPERTY', 'Объекты недвижимости'), ('LAYOUT', 'Планировки'), ('DISCOUNT', 'Скидки'), ('DEAL', 'Сделки'), ('PAYMENT', 'Платежи'), ('PAYMENT_TYPE', 'Типы платежей'), ('BENEFICIARY_ACCOUNT', 'Счета получателей'), ('TEMPLATE', 'Шаблоны документов'), ('REPORT', 'Отчеты'), ('PLAN', 'Планы продаж'), ('TASK', 'Задачи'), ('TASK_LOG', 'Логи задач'), ('USER', 'Пользователи'), ('ROLE', 'Роли'), ('PERMISSION', 'Разрешения'), ('COMPANY', 'Компании'), ('DEPARTMENT', 'Отделы'), ('DASHBOARD', 'Дашборд'), ('SETTINGS', 'Настройки')], max_length=50, verbose_name='Ресурс'),
        ),
        migrations.CreateModel(
            name='PartnerAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название партнёра')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='API ключ')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия')),
                ('allowed_ips', models.TextField(blank=True, help_text='Список IP-адресов через запятую. Пустое поле = без ограничений', verbose_name='Разрешённые IP')),
                ('requests_per_minute', models.PositiveIntegerField(default=60, verbose_name='Запросов в минуту')),
                ('requests_per_day', models.PositiveIntegerField(default=10000, verbose_name='Запросов в день')),
                ('company', models.ForeignKey(help_text='Компания, к данным которой будет доступ', on_delete=django.db.models.deletion.CASCADE, related_name='partner_api_keys', to='permissions.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'API ключ партнёра',
                'verbose_name_plural': 'API ключи партнёров',
                'ordering': ['-created_at'],
            },
        ),
    ]
