# Generated by Django 5.2.6 on 2025-12-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_add_partner_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerapikey',
            name='company',
        ),
        migrations.AddField(
            model_name='partnerapikey',
            name='companies',
            field=models.ManyToManyField(blank=True, help_text='Компании, к данным которых будет доступ', related_name='partner_api_keys', to='permissions.company', verbose_name='Компании'),
        ),
    ]
