# Generated by Django 5.2.6 on 2025-12-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_change_partner_api_key_to_many_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapikey',
            name='allowed_scopes',
            field=models.JSONField(default=list, help_text='Список разрешённых действий: VIEW_PROJECTS, VIEW_BUILDINGS, CREATE_APPLICATION', verbose_name='Разрешённые действия'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(choices=[('CLIENT', 'Клиенты'), ('APPLICATION', 'Заявки'), ('MEETING', 'Встречи'), ('PROJECT', 'Проекты'), ('BUILDING', 'Дома'), ('BUILDING_TYPE', 'Типы домов'), ('PROPERTY', 'Объекты недвижимости'), ('LAYOUT', 'Планировки'), ('DISCOUNT', 'Скидки'), ('DEAL', 'Сделки'), ('PAYMENT', 'Платежи'), ('PAYMENT_TYPE', 'Типы платежей'), ('BENEFICIARY_ACCOUNT', 'Счета получателей'), ('TEMPLATE', 'Шаблоны документов'), ('REPORT', 'Отчеты'), ('PLAN', 'Планы продаж'), ('TASK', 'Задачи'), ('TASK_LOG', 'Логи задач'), ('USER', 'Пользователи'), ('ROLE', 'Роли'), ('PERMISSION', 'Разрешения'), ('COMPANY', 'Компании'), ('DEPARTMENT', 'Отделы'), ('PARTNER_API_KEY', 'API-ключи партнёров'), ('DASHBOARD', 'Дашборд'), ('SETTINGS', 'Настройки')], max_length=50, verbose_name='Ресурс'),
        ),
    ]
