# Generated by Django 5.2.6 on 2026-03-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0010_encrypt_api_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerapikey',
            name='key_encrypted',
            field=models.TextField(editable=False, verbose_name='Зашифрованный API ключ'),
        ),
    ]
