# Generated by Django 5.2.6 on 2026-10-05 09:12

import permissions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0011_alter_partnerapikey_key_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deal_currency',
            field=models.CharField(default='UZS', max_length=3, verbose_name='Валюта сделок'),
        ),
        migrations.AddField(
            model_name='company',
            name='supported_currencies',
            field=models.JSONField(default=permissions.models.default_supported_currencies, verbose_name='Поддерживаемые валюты'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(choices=[('CLIENT', 'Клиенты'), ('APPLICATION', 'Заявки'), ('APPLICATION_STATUS', 'Статусы заявок'), ('MEETING', 'Встречи'), ('PROJECT', 'Проекты'), ('BUILDING', 'Дома'), ('BUILDING_TYPE', 'Типы домов'), ('PROPERTY', 'Объекты недвижимости'), ('LAYOUT', 'Планировки'), ('DISCOUNT', 'Скидки'), ('DEAL', 'Сделки'), ('PAYMENT', 'Платежи'), ('PAYMENT_TYPE', 'Типы платежей'), ('BENEFICIARY_ACCOUNT', 'Счета получателей'), ('TEMPLATE', 'Шаблоны документов'), ('REPORT', 'Отчеты'), ('PLAN', 'Планы продаж'), ('TASK', 'Задачи'), ('TASK_LOG', 'Логи задач'), ('USER', 'Пользователи'), ('ROLE', 'Роли'), ('PERMISSION', 'Разрешения'), ('COMPANY', 'Компании'), ('DEPARTMENT', 'Отделы'), ('PARTNER_API_KEY', 'API-ключи партнёров'), ('EXCHANGE_RATE', 'Курсы валют'), ('DASHBOARD', 'Дашборд'), ('SETTINGS', 'Настройки')], max_length=50, verbose_name='Ресурс'),
        ),
    ]
