# Generated by Django 5.2.6 on 2025-09-18 15:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название или номер дома/корпуса')),
                ('floors_count', models.PositiveIntegerField(verbose_name='Количество этажей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='realty.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Квартира'), ('COMMERCIAL', 'Коммерция'), ('PARKING', 'Парковка'), ('STORAGE', 'Кладовка'), ('COTTAGE', 'Коттедж')], max_length=20, verbose_name='Тип объекта')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('unit_number', models.CharField(max_length=20, verbose_name='Номер объекта (кв, парковки и т.д.)')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь (кв.м)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('status', models.CharField(choices=[('AVAILABLE', 'В продаже'), ('BOOKED', 'Забронировано'), ('SOLD', 'Продано')], default='AVAILABLE', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='realty.building', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'unique_together': {('building', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название скидки')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Процент'), ('FIXED_AMOUNT', 'Фиксированная сумма')], max_length=20, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Значение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('properties', models.ManyToManyField(blank=True, related_name='discounts', to='realty.property', verbose_name='Объекты со скидкой')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
    ]
