# Generated by Django 5.2.6 on 2025-09-18 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AddField(
            model_name='project',
            name='developer_details',
            field=models.TextField(blank=True, verbose_name='Реквизиты застройщика'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/logos/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='project',
            name='max_floors',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этажность (макс)'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_floors',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этажность (мин)'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменен'),
        ),
        migrations.AddField(
            model_name='project',
            name='usp_1',
            field=models.TextField(blank=True, verbose_name='УТП 1'),
        ),
        migrations.AddField(
            model_name='project',
            name='usp_2',
            field=models.TextField(blank=True, verbose_name='УТП 2'),
        ),
        migrations.AddField(
            model_name='project',
            name='usp_3',
            field=models.TextField(blank=True, verbose_name='УТП 3'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись к фото')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='realty.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фотография проекта',
                'verbose_name_plural': 'Галерея проекта',
            },
        ),
    ]
