# Generated by Django 5.2.6 on 2025-09-18 15:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_alter_project_options_project_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объект недвижимости', 'verbose_name_plural': 'Объекты недвижимости'},
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AddField(
            model_name='property',
            name='entrance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_finishing',
            field=models.BooleanField(default=False, verbose_name='Наличие отделки'),
        ),
        migrations.AddField(
            model_name='property',
            name='layout_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наименование планировки'),
        ),
        migrations.AddField(
            model_name='property',
            name='riser',
            field=models.CharField(blank=True, max_length=20, verbose_name='Стояк'),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_properties', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменен'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Этаж'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='property',
            name='unit_number',
            field=models.CharField(max_length=20, verbose_name='Номер объекта'),
        ),
    ]
