# Generated by Django 5.2.6 on 2025-09-18 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_alter_property_options_property_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип дома',
                'verbose_name_plural': 'Типы домов',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='address_detail',
            field=models.CharField(blank=True, max_length=255, verbose_name='Точный адрес дома'),
        ),
        migrations.AddField(
            model_name='building',
            name='cadastre_date_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Дата кадастра (Факт)'),
        ),
        migrations.AddField(
            model_name='building',
            name='cadastre_date_plan',
            field=models.DateField(blank=True, null=True, verbose_name='Дата кадастра (План)'),
        ),
        migrations.AddField(
            model_name='building',
            name='ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Высота потолков (м)'),
        ),
        migrations.AddField(
            model_name='building',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_buildings', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AddField(
            model_name='building',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='buildings', to='realty.discount', verbose_name='Скидки на дом'),
        ),
        migrations.AddField(
            model_name='building',
            name='material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='building',
            name='sales_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старта продаж'),
        ),
        migrations.AddField(
            model_name='building',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'На проверке'), ('FOR_SALE', 'В продаже'), ('COMPLETED', 'Сдан'), ('ARCHIVED', 'В архиве')], default='UNDER_REVIEW', max_length=20, verbose_name='Статус дома'),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_buildings', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменен'),
        ),
        migrations.AddField(
            model_name='building',
            name='usp_1',
            field=models.TextField(blank=True, verbose_name='УТП 1'),
        ),
        migrations.AddField(
            model_name='building',
            name='usp_2',
            field=models.TextField(blank=True, verbose_name='УТП 2'),
        ),
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='buildings/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись к фото')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='realty.building', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Фотография дома',
                'verbose_name_plural': 'Галерея дома',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='building_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realty.buildingtype', verbose_name='Тип дома'),
        ),
    ]
