# Generated by Django 5.2.6 on 2025-09-18 15:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_buildingtype_building_address_detail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-start_date'], 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='value',
        ),
        migrations.AddField(
            model_name='discount',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана'),
        ),
        migrations.AddField(
            model_name='discount',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия (бессрочная, если пусто)'),
        ),
        migrations.AddField(
            model_name='discount',
            name='percentage_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Значение в процентах (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='property_type',
            field=models.CharField(blank=True, choices=[('APARTMENT', 'Квартира'), ('COMMERCIAL', 'Коммерция'), ('PARKING', 'Парковка'), ('STORAGE', 'Кладовка'), ('COTTAGE', 'Коттедж')], max_length=20, null=True, verbose_name='Тип недвижимости для скидки'),
        ),
        migrations.AddField(
            model_name='discount',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала действия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='discount',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменена'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='realty.property', verbose_name='Конкретные объекты со скидкой'),
        ),
    ]
