# Generated by Django 5.2.6 on 2025-09-29 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_buildinglog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildinglog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог дома', 'verbose_name_plural': 'Логи домов'},
        ),
        migrations.RemoveField(
            model_name='building',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='property',
            name='layout_name',
        ),
        migrations.AddField(
            model_name='discount',
            name='buildings',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='realty.building', verbose_name='Привязать к домам'),
        ),
        migrations.AddField(
            model_name='project',
            name='cadastre_date_plan',
            field=models.DateField(blank=True, null=True, verbose_name='Дата кадастра (План)'),
        ),
        migrations.AlterField(
            model_name='buildinglog',
            name='action',
            field=models.TextField(verbose_name='Совершенное действие'),
        ),
        migrations.AlterField(
            model_name='buildinglog',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='realty.building', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='buildinglog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='buildinglog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('SELECTION', 'Подбор'), ('RESERVE', 'Резерв'), ('BOOKING', 'Бронь'), ('IN_DEAL', 'Сделка в работе'), ('SOLD', 'Сделка проведена')], default='SELECTION', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='DiscountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Совершенное действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='realty.discount', verbose_name='Скидка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог скидки',
                'verbose_name_plural': 'Логи скидок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название планировки')),
                ('main_layout_image', models.ImageField(blank=True, null=True, upload_to='layouts/main/', verbose_name='Планировка')),
                ('extra_layout_image', models.ImageField(blank=True, null=True, upload_to='layouts/extra/', verbose_name='Доп. планировка')),
                ('floor_plan_image', models.ImageField(blank=True, null=True, upload_to='layouts/floor_plans/', verbose_name='Расположение на этаже')),
                ('usp_image', models.ImageField(blank=True, null=True, upload_to='layouts/usp/', verbose_name='УТП фото')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='realty.building', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировки',
                'unique_together': {('building', 'name')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='realty.layout', verbose_name='Планировка'),
        ),
    ]
