# Generated by Django 5.2.6 on 2026-01-11 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_add_allowed_scopes_to_partner_api_key'),
        ('realty', '0007_alter_buildinglog_options_remove_building_discounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='permissions.company', verbose_name='Компания'),
        ),
    ]
