# Generated by Django 5.2.6 on 2026-01-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0008_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='entrance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Подъезд'),
        ),
    ]
