# Generated by Django 5.2.6 on 2026-01-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0009_change_entrance_to_charfield'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('building', 'unit_number', 'entrance')},
        ),
    ]
