# Generated by Django 5.2.6 on 2026-01-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0010_change_unique_together_add_entrance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('building', 'unit_number', 'entrance', 'floor')},
        ),
    ]
