# Generated by Django 5.2.6 on 2026-09-10 04:58

import django.db.models.deletion
from django.db import migrations, models


def fill_discount_company(apps, schema_editor):
    """
    Проставляет компанию существующим скидкам по домам, к которым они привязаны.

    Скидки без домов остаются без компании: определить владельца по данным
    нельзя, а показывать их всем компаниям — ровно та утечка, ради которой
    поле и добавлено. Такие записи увидит только системный администратор.
    """
    Discount = apps.get_model('realty', 'Discount')
    for discount in Discount.objects.filter(company__isnull=True).prefetch_related('buildings__project'):
        building = discount.buildings.first()
        if building and building.project and building.project.company_id:
            discount.company_id = building.project.company_id
            discount.save(update_fields=['company'])


def unfill_discount_company(apps, schema_editor):
    """Откат: поле удаляется вместе с данными, отдельных действий не требуется."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0011_alter_partnerapikey_key_encrypted'),
        ('realty', '0011_add_floor_to_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='permissions.company', verbose_name='Компания'),
        ),
        migrations.RunPython(fill_discount_company, unfill_discount_company),
    ]
