# Generated by Django 5.2.6 on 2026-09-10 05:42

from django.db import migrations


def check_duplicates(apps, schema_editor):
    """
    Останавливает миграцию, если в доме есть объекты с одинаковым номером.

    Прежнее ограничение допускало такие записи, поэтому в рабочей базе они
    могут существовать. Молча слить или переименовать их нельзя — за каждым
    номером стоят цены, планировки и, возможно, сделки. Список дублей
    показывает команда:

        python manage.py find_duplicate_units
    """
    from django.db.models import Count

    Property = apps.get_model('realty', 'Property')
    duplicates = (
        Property.objects.values('building_id', 'unit_number')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
        .order_by('building_id', 'unit_number')
    )
    found = list(duplicates[:20])
    if not found:
        return

    total = duplicates.count()
    message = [
        f"Нельзя сделать номер объекта уникальным в доме: найдены повторы ({total} шт.)."
    ]
    message += [
        f"  дом #{row['building_id']}, номер «{row['unit_number']}» — {row['n']} объекта"
        for row in found
    ]
    message += ["", "Разберите их вручную: python manage.py find_duplicate_units"]
    raise RuntimeError(chr(10).join(message))


def noop(apps, schema_editor):
    """Откат: ограничение снимается, проверка не нужна."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0012_add_company_to_discount'),
    ]

    operations = [
        migrations.RunPython(check_duplicates, noop),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('building', 'unit_number')},
        ),
    ]
