# Generated by Django 5.2.6 on 2026-09-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0011_alter_partnerapikey_key_encrypted'),
        ('realty', '0013_unit_number_unique_per_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='permissions.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название типа'),
        ),
        migrations.AlterUniqueTogether(
            name='buildingtype',
            unique_together={('company', 'name')},
        ),
    ]
