# Generated by Django 5.2.6 on 2026-10-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0014_company_isolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price_currency',
            field=models.CharField(choices=[('UZS', 'Узбекский сум'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Российский рубль'), ('CNY', 'Китайский юань'), ('KZT', 'Казахстанский тенге'), ('GBP', 'Фунт стерлингов'), ('AED', 'Дирхам ОАЭ'), ('TRY', 'Турецкая лира')], default='UZS', max_length=3, verbose_name='Валюта прайса'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Стоимость'),
        ),
    ]
