# Generated by Django 5.2.6 on 2026-10-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_discount_payment_plans'),
        ('realty', '0015_multicurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='payment_plans',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='finances.paymenttype', verbose_name='Только для планов оплаты'),
        ),
    ]
