"""
Django settings for real_estate_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-!l5n0q200=_=x@&(n=mo65t$#))vha%zdlo8gqk$w+9^yg9^(t')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Парсинг ALLOWED_HOSTS из переменной окружения
_allowed_hosts_env = config('ALLOWED_HOSTS', default='')
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'c0s9w1gq-8000.euw.devtunnels.ms',  # Tunnel для бэкенда (на всякий случай)
    'backend',  # Docker service name
    'dvgroup.uz',  # Production domain
    'www.dvgroup.uz',  # Production domain with www
] + [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]

# Парсинг CORS_ORIGINS из переменной окружения (для production сервера)
_cors_origins_env = config('CORS_ORIGINS', default='')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.realty.apps.RealtyConfig',
    'apps.crm.apps.CrmConfig',
    'apps.deals',
    'apps.finances',
    'apps.tasks.apps.TasksConfig',  # Система управления задачами
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Для blacklist токенов при выходе
    'apps.documents.apps.DocumentsConfig',
    'django_filters',
    'apps.reports',
    'permissions',  # Система разрешений и ролей
    'drf_spectacular',  # OpenAPI/Swagger документация
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ← CORS должен быть здесь, перед CommonMiddleware!
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'real_estate_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'real_estate_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Переключение между PostgreSQL и SQLite
USE_SQLITE = config('USE_SQLITE', default=True, cast=bool)

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='crm_database'),
            'USER': config('DB_USER', default='crm_user'),
            'PASSWORD': config('DB_PASSWORD', default='crm_password'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Статические файлы для production (collectstatic)
STATIC_ROOT = BASE_DIR / 'staticfiles'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Ваш фронтенд
    "http://127.0.0.1:5173",  # Альтернативный адрес
    "http://localhost:5174",
    "http://localhost:5175",  # Для друга
    "http://localhost:5176",  # Дополнительный порт
    "http://localhost",       # Docker frontend (port 80)
    "http://localhost:80",    # Docker frontend explicit
    "http://frontend",        # Docker service name
    'https://5mpxwrp0-5174.euw.devtunnels.ms',
    'https://c0s9w1gq-5173.euw.devtunnels.ms',
    'https://c0s9w1gq-8000.euw.devtunnels.ms',
    'https://tws483gv-5173.euw.devtunnels.ms',
    'https://tws483gv-8000.euw.devtunnels.ms',
    # Production domain
    'https://dvgroup.uz',
    'https://www.dvgroup.uz',
    'http://dvgroup.uz',
    'http://www.dvgroup.uz',
] + [o.strip() for o in _cors_origins_env.split(',') if o.strip()]

# Дополнительные настройки CORS для работы с JWT
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False  # Явно указываем, что разрешаем только указанные origins

# Для отладки CORS - временно включите если проблема не решится
# CORS_ALLOW_ALL_ORIGINS = True  # Раскомментируйте для отладки

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Rate limiting для защиты от брутфорса
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',      # Анонимные запросы (для /public/ с API-ключом)
        'user': '1000/hour',     # Аутентифицированные пользователи
    }
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Real Estate CRM API',
    'DESCRIPTION': '''
API для системы управления недвижимостью.

## Аутентификация

### Для внутренних пользователей CRM
Используйте JWT токены. Получите токен через `/api/token/` и передавайте в заголовке:
```
Authorization: Bearer <access_token>
```

### Для партнёров (публичный API)
Эндпоинты `/api/public/*` требуют API-ключ партнёра. Передавайте ключ в заголовке:
```
X-API-Key: <ваш_api_ключ>
```

API-ключи выдаются администратором системы и могут иметь ограничения:
- Срок действия
- Белый список IP-адресов  
- Лимиты запросов (в минуту/день)
- Доступ только к данным определённых компаний
''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    # Описание схем безопасности
    'SECURITY': [
        {'BearerAuth': []},
    ],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'JWT токен для внутренних пользователей CRM. Получите через POST /api/token/'
            },
            'ApiKeyAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'X-API-Key',
                'description': 'API-ключ партнёра для доступа к публичному API (/api/public/*)'
            }
        }
    },
    'TAGS': [
        {'name': 'Public API', 'description': 'Публичный API для партнёров (требует X-API-Key)'},
        {'name': 'Auth', 'description': 'Аутентификация и токены'},
        {'name': 'CRM', 'description': 'Клиенты и заявки'},
        {'name': 'Deals', 'description': 'Сделки'},
        {'name': 'Realty', 'description': 'Проекты, здания, квартиры'},
        {'name': 'Finances', 'description': 'Платежи и финансы'},
        {'name': 'Tasks', 'description': 'Задачи'},
        {'name': 'Permissions', 'description': 'Роли и разрешения'},
    ],
}

# Кастомный backend для проверки разрешений
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Стандартный backend
    'permissions.backends.PermissionBackend',  # Наш кастомный backend
]
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=5),       # access-токен будет жить 5 часов (для разработки)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),      # refresh-токен будет жить 30 дней
    "ROTATE_REFRESH_TOKENS": True,                     # При обновлении refresh-токен также будет заменяться на новый
    "BLACKLIST_AFTER_ROTATION": True,                  # Старый refresh-токен будет добавлен в черный список
    "UPDATE_LAST_LOGIN": True,                         # Обновлять поле last_login у пользователя при входе
}
SITE_URL = 'http://127.0.0.1:8000'

# Email settings (для восстановления пароля)
# В продакшене замените на реальные настройки SMTP
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Для разработки - письма в консоль
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Для продакшена
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
DEFAULT_FROM_EMAIL = 'noreply@crm.local'
FRONTEND_URL = 'http://localhost:5173'  # URL фронтенда для ссылок в письмах

# =============================================================================
# НАСТРОЙКИ БЕЗОПАСНОСТИ (для продакшена)
# =============================================================================
# Включить в продакшене для принудительного использования HTTPS
if not DEBUG:
    # Перенаправление HTTP → HTTPS (отключить если нет SSL)
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
    
    # HSTS (HTTP Strict Transport Security) - только если есть SSL
    if SECURE_SSL_REDIRECT:
        SECURE_HSTS_SECONDS = 31536000  # 1 год
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
    
    # Защита cookies (только если есть SSL)
    SESSION_COOKIE_SECURE = SECURE_SSL_REDIRECT
    CSRF_COOKIE_SECURE = SECURE_SSL_REDIRECT
    
    # Прокси-заголовки (если за nginx/load balancer)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF_TRUSTED_ORIGINS для production (из переменной окружения)
_csrf_trusted_env = config('CSRF_TRUSTED_ORIGINS', default='')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted_env.split(',') if o.strip()]
