# Generated by Django 5.2.6 on 2025-11-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_with_delay',
            field=models.BooleanField(default=False, verbose_name='Завершена с просрочкой'),
        ),
    ]
