# Generated by Django 5.2.6 on 2025-09-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realty', '0007_alter_buildinglog_options_remove_building_discounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('file', models.FileField(upload_to='templates/', verbose_name='Файл шаблона (.docx)')),
                ('applies_to_property_types', models.JSONField(blank=True, default=list, verbose_name='Применять для типов недвижимости')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_buildings', models.ManyToManyField(blank=True, to='realty.building', verbose_name='Применять для домов')),
                ('applies_to_projects', models.ManyToManyField(blank=True, to='realty.project', verbose_name='Применять для проектов')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['-created_at'],
            },
        ),
    ]
