# Generated by Django 5.2.6 on 2026-09-10 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_template_company_template_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(upload_to='templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Файл шаблона (.docx)'),
        ),
    ]
