# Generated by Django 5.2.6 on 2025-09-18 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='responsible_manager',
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Холост/Не замужем'), ('MARRIED', 'Женат/Замужем'), ('DIVORCED', 'В разводе'), ('WIDOWED', 'Вдовец/Вдова')], max_length=10, verbose_name='Семейный статус'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Когда выдан паспорт'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_series_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер и серия паспорта'),
        ),
        migrations.AddField(
            model_name='client',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, verbose_name='ПИНФЛ'),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_address',
            field=models.TextField(blank=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='client',
            name='relatives',
            field=models.ManyToManyField(blank=True, to='crm.client', verbose_name='Родственники'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Совершенное действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.client', verbose_name='Клиент')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог клиента',
                'verbose_name_plural': 'Логи клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
