# Generated by Django 5.2.6 on 2025-09-18 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_application_options_alter_client_options_and_more'),
        ('realty', '0005_alter_discount_options_remove_discount_discount_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='property',
        ),
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создана (менеджер)'),
        ),
        migrations.AddField(
            model_name='application',
            name='interested_projects',
            field=models.ManyToManyField(blank=True, to='realty.project', verbose_name='Интересующие проекты'),
        ),
        migrations.AddField(
            model_name='application',
            name='interested_property_type',
            field=models.CharField(blank=True, choices=[('APARTMENT', 'Квартира'), ('COMMERCIAL', 'Коммерция'), ('PARKING', 'Парковка'), ('STORAGE', 'Кладовка'), ('COTTAGE', 'Коттедж')], max_length=20, verbose_name='Интересующий тип недвижимости'),
        ),
        migrations.AddField(
            model_name='application',
            name='max_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Площадь до (кв.м)'),
        ),
        migrations.AddField(
            model_name='application',
            name='max_floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж до'),
        ),
        migrations.AddField(
            model_name='application',
            name='min_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Площадь от (кв.м)'),
        ),
        migrations.AddField(
            model_name='application',
            name='min_floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж от'),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('INTERNET', 'Интернет'), ('SOCIAL_MEDIA', 'Соц.сети'), ('OFFICE', 'Офис'), ('CALL', 'Звонок')], default='CALL', max_length=20, verbose_name='Источник'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Совершенное действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.application', verbose_name='Заявка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог заявки',
                'verbose_name_plural': 'Логи заявок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreciseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название точного источника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
            ],
            options={
                'verbose_name': 'Точный источник',
                'verbose_name_plural': 'Точные источники',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='precise_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.precisesource', verbose_name='Точный источник'),
        ),
    ]
