# Generated by Django 5.2.6 on 2025-09-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_application_property_application_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Причина отказа',
                'verbose_name_plural': 'Причины отказа',
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('JUNK', 'Нецелевая'), ('REJECTED', 'Отказ'), ('CLOSED_WON', 'Успешно закрыта'), ('CLOSED_LOST', 'Неуспешно закрыта')], default='NEW', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.rejectionreason', verbose_name='Причина (отказ/нецелевая)'),
        ),
    ]
