# Generated by Django 5.2.6 on 2025-09-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rejectionreason_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejectionreason',
            options={},
        ),
        migrations.AddField(
            model_name='rejectionreason',
            name='reason_type',
            field=models.CharField(choices=[('JUNK', 'Нецелевая'), ('REJECTED', 'Отказ')], default='Нет денег', max_length=10, verbose_name='Тип причины'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rejectionreason',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Причина'),
        ),
    ]
