# Generated by Django 5.2.6 on 2025-09-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_rejectionreason_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectionreason',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
