# Generated by Django 5.2.6 on 2025-09-29 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rejectionreason_is_active'),
        ('realty', '0007_alter_buildinglog_options_remove_building_discounts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='passport_series_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='client',
            name='billing_address',
            field=models.TextField(blank=True, verbose_name='Расчетный адрес'),
        ),
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='client',
            name='file_storage_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на хранилище файлов'),
        ),
        migrations.AddField(
            model_name='client',
            name='inn',
            field=models.CharField(blank=True, max_length=14, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_series',
            field=models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активный'), ('INACTIVE', 'Неактивный'), ('ARCHIVED', 'В архиве')], default='ACTIVE', max_length=10, verbose_name='Статус клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_address',
            field=models.TextField(blank=True, verbose_name='Адрес прописки'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Новая встреча'), ('COMPLETED', 'Встреча состоялась'), ('CANCELLED', 'Встреча не состоялась')], default='NEW', max_length=20, verbose_name='Статус')),
                ('planned_date', models.DateTimeField(verbose_name='Плановая дата и время')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата и время')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к встрече')),
                ('result_comment', models.TextField(blank=True, verbose_name='Результат встречи')),
                ('is_auto_created', models.BooleanField(default=False, verbose_name='Создана автоматически')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='crm.application', verbose_name='Заявка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='crm.client', verbose_name='Клиент')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Постановщик')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('interested_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realty.building', verbose_name='Интересующий дом')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Совершенное действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.meeting', verbose_name='Встреча')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог встречи',
                'verbose_name_plural': 'Логи встреч',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='crm.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Номер телефона клиента',
                'verbose_name_plural': 'Номера телефонов клиента',
                'unique_together': {('client', 'phone_number')},
            },
        ),
    ]
