# Generated by Django 5.2.6 on 2026-01-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_client_file_storage_link_clientfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код статуса')),
                ('name', models.CharField(max_length=100, verbose_name='Название статуса')),
                ('color', models.CharField(default='#9e9e9e', max_length=7, verbose_name='Цвет (HEX)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('JUNK', 'Нецелевая'), ('REJECTED', 'Отказ'), ('CLOSED_WON', 'Успешно закрыта'), ('CLOSED_LOST', 'Неуспешно закрыта')], default='NEW', max_length=50, verbose_name='Статус заявки'),
        ),
    ]
