# Generated by Django 5.2.6 on 2026-09-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_soft_delete_application_meeting'),
        ('permissions', '0011_alter_partnerapikey_key_encrypted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejectionreason',
            options={'verbose_name': 'Причина отказа', 'verbose_name_plural': 'Причины отказа'},
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='permissions.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='precisesource',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='permissions.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='rejectionreason',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='permissions.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код статуса'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='precisesource',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название точного источника'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationstatus',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('company', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='precisesource',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='rejectionreason',
            unique_together={('company', 'name', 'reason_type')},
        ),
    ]
