# Generated by Django 5.2.6 on 2026-09-10 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_company_isolation'),
        ('permissions', '0011_alter_partnerapikey_key_encrypted'),
        ('realty', '0014_company_isolation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['company', 'status', 'is_deleted'], name='crm_applica_company_c95366_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['client', 'is_deleted'], name='crm_applica_client__6fb54c_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_by', '-created_at'], name='crm_applica_created_4e8bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['updated_at'], name='crm_applica_updated_2ef4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'status'], name='crm_client_company_79b629_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_by', '-created_at'], name='crm_client_created_50cce6_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'planned_date'], name='crm_meeting_status_23ecb3_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['executor', 'status'], name='crm_meeting_executo_a0b583_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['company', 'is_deleted'], name='crm_meeting_company_ec71ed_idx'),
        ),
    ]
