# Generated by Django 5.2.6 on 2026-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientphonenumber',
            index=models.Index(fields=['phone_number'], name='crm_clientp_phone_n_311ba3_idx'),
        ),
    ]
