# Generated by Django 5.2.6 on 2025-11-20 16:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realty', '0007_alter_buildinglog_options_remove_building_discounts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Месяц')),
                ('contracting_units_plan', models.IntegerField(default=0, verbose_name='План по контрактации (штуки)')),
                ('contracting_money_plan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='План по контрактации (деньги)')),
                ('revenue_money_plan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='План по поступлениям (деньги)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'План продаж (по сотрудникам)',
                'verbose_name_plural': 'Планы продаж (по сотрудникам)',
                'ordering': ['employee', 'year', 'month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Месяц')),
                ('contracting_units_plan', models.IntegerField(default=0, verbose_name='План по контрактации (штуки)')),
                ('contracting_money_plan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='План по контрактации (деньги)')),
                ('revenue_money_plan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='План по поступлениям (деньги)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'План продаж (по проектам)',
                'verbose_name_plural': 'Планы продаж (по проектам)',
                'ordering': ['project', 'year', 'month'],
                'unique_together': {('project', 'year', 'month')},
            },
        ),
    ]
