# Generated by Django 5.2.6 on 2026-10-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_audit_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeplan',
            name='contracting_money_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='План по контрактации (деньги)'),
        ),
        migrations.AlterField(
            model_name='employeeplan',
            name='revenue_money_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='План по поступлениям (деньги)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='contracting_money_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='План по контрактации (деньги)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='revenue_money_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='План по поступлениям (деньги)'),
        ),
    ]
