# Generated by Django 5.2.6 on 2025-09-18 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_remove_application_property_application_created_by_and_more'),
        ('realty', '0005_alter_discount_options_remove_discount_discount_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название типа оплаты')),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Типы оплат',
            },
        ),
        migrations.CreateModel(
            name='PurchasePurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название цели')),
            ],
            options={
                'verbose_name': 'Цель приобретения',
                'verbose_name_plural': 'Цели приобретения',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKING', 'Бронь'), ('IN_PROGRESS', 'В работе'), ('CLOSED_WON', 'Успешно закрыта'), ('CANCELLED', 'Отменена')], default='BOOKING', max_length=20, verbose_name='Статус сделки')),
                ('booking_start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала брони')),
                ('booking_end_date', models.DateTimeField(verbose_name='Плановая дата окончания брони')),
                ('contract_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость по договору')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('applied_discounts', models.ManyToManyField(blank=True, to='realty.discount', verbose_name='Примененные скидки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deal', to='realty.property', verbose_name='Объект недвижимости')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.paymenttype', verbose_name='Тип оплаты')),
                ('purchase_purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.purchasepurpose', verbose_name='Цель приобретения')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Совершенное действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='deals.deal', verbose_name='Сделка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог сделки',
                'verbose_name_plural': 'Логи сделок',
                'ordering': ['-created_at'],
            },
        ),
    ]
