# Generated by Django 5.2.6 on 2025-09-29 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('realty', '0007_alter_buildinglog_options_remove_building_discounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='deal',
            name='client_signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписания клиентом'),
        ),
        migrations.AddField(
            model_name='deal',
            name='company_signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписания компанией'),
        ),
        migrations.AddField(
            model_name='deal',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='deal',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='deal',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Стоимость на момент начала сделки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='initial_price_per_sqm',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Цена за м² на момент начала сделки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечание к сделке'),
        ),
        migrations.AddField(
            model_name='deal',
            name='signed_document_scan',
            field=models.FileField(blank=True, null=True, upload_to='deals/signed_documents/', verbose_name='Скан подписанного документа'),
        ),
        migrations.AddField(
            model_name='deal',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата расторжения'),
        ),
        migrations.AddField(
            model_name='deal',
            name='termination_document_scan',
            field=models.FileField(blank=True, null=True, upload_to='deals/termination_documents/', verbose_name='Скан документа о расторжении'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='realty.property', verbose_name='Объект недвижимости'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('BOOKING', 'Бронь'), ('IN_PROGRESS', 'В работе'), ('CLOSED_WON', 'Успешно закрыта'), ('CANCELLED', 'Отменена'), ('TERMINATED', 'Расторгнута')], default='BOOKING', max_length=20, verbose_name='Статус сделки'),
        ),
    ]
