# Generated by Django 5.2.6 on 2026-02-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_cancellation_reason_deal_client_signature_date_and_more'),
        ('permissions', '0008_alter_partnerapikey_allowed_scopes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='permissions.company', verbose_name='Компания'),
        ),
    ]
