# Generated by Django 5.2.6 on 2026-09-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='currency',
            field=models.CharField(choices=[('UZS', 'Узбекский сум'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='UZS', max_length=3, verbose_name='Валюта сделки'),
        ),
    ]
