# Generated by Django 5.2.6 on 2026-09-10 05:09

from django.db import migrations, models


def fill_closed_at(apps, schema_editor):
    """
    Проставляет дату закрытия уже закрытым сделкам.

    Берём дату договора (это и есть момент контрактации), а если её нет —
    время последнего изменения: другой отметки о закрытии в данных не осталось.
    """
    from datetime import datetime, time
    from django.utils import timezone

    Deal = apps.get_model('deals', 'Deal')
    for deal in Deal.objects.filter(status='CLOSED_WON', closed_at__isnull=True):
        if deal.contract_date:
            moment = datetime.combine(deal.contract_date, time.min)
            deal.closed_at = timezone.make_aware(moment) if timezone.is_naive(moment) else moment
        else:
            deal.closed_at = deal.updated_at
        deal.save(update_fields=['closed_at'])


def unfill_closed_at(apps, schema_editor):
    """Откат: поле удаляется вместе с данными."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_add_currency_to_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата успешного закрытия'),
        ),
    
        migrations.RunPython(fill_closed_at, unfill_closed_at),
    ]
