# Generated by Django 5.2.6 on 2026-09-10 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_seed_application_statuses'),
        ('deals', '0005_add_closed_at_to_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.application', verbose_name='Заявка'),
        ),
    ]
