# Generated by Django 5.2.6 on 2026-09-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_add_application_to_deal'),
        ('permissions', '0011_alter_partnerapikey_key_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='permissions.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='purchasepurpose',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='permissions.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название типа оплаты'),
        ),
        migrations.AlterField(
            model_name='purchasepurpose',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название цели'),
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('company', 'contract_number')},
        ),
        migrations.AlterUniqueTogether(
            name='paymenttype',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='purchasepurpose',
            unique_together={('company', 'name')},
        ),
    ]
