# Generated by Django 5.2.6 on 2026-09-10 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_performance_indexes'),
        ('deals', '0007_company_isolation'),
        ('permissions', '0011_alter_partnerapikey_key_encrypted'),
        ('realty', '0014_company_isolation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'status'], name='deals_deal_company_344c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status', '-created_at'], name='deals_deal_status_ee4474_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_by', 'status'], name='deals_deal_created_e62073_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['closed_at'], name='deals_deal_closed__d7ba0e_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['contract_date'], name='deals_deal_contrac_ae3b74_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['booking_end_date'], name='deals_deal_booking_78a970_idx'),
        ),
    ]
