# Generated by Django 5.2.6 on 2026-10-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='catalog_currency',
            field=models.CharField(blank=True, choices=[('UZS', 'Узбекский сум'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Российский рубль'), ('CNY', 'Китайский юань'), ('KZT', 'Казахстанский тенге'), ('GBP', 'Фунт стерлингов'), ('AED', 'Дирхам ОАЭ'), ('TRY', 'Турецкая лира')], max_length=3, verbose_name='Валюта прайса'),
        ),
        migrations.AddField(
            model_name='deal',
            name='catalog_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Цена по прайсу'),
        ),
        migrations.AddField(
            model_name='deal',
            name='catalog_rate',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Курс пересчёта прайса в валюту сделки'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contract_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Стоимость по договору'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='currency',
            field=models.CharField(choices=[('UZS', 'Узбекский сум'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('RUB', 'Российский рубль'), ('CNY', 'Китайский юань'), ('KZT', 'Казахстанский тенге'), ('GBP', 'Фунт стерлингов'), ('AED', 'Дирхам ОАЭ'), ('TRY', 'Турецкая лира')], default='UZS', max_length=3, verbose_name='Валюта сделки'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Стоимость на момент начала сделки'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='initial_price_per_sqm',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Цена за м² на момент начала сделки'),
        ),
    ]
