# Generated by Django 5.2.6 on 2026-10-06 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_multicurrency'),
        ('finances', '0010_discount_payment_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='payment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='finances.paymenttype', verbose_name='План оплаты'),
        ),
    ]
